# -*- coding: utf-8 -*-
"""Linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dvUcEjdw8ch8H4Y0YB3Dxg56JwisbNy
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mamtawardhani/Datasets-for-linear-and-logistic-regression/main/greToefl.csv")
# print(df)

TOEFL_Score = df["TOEFL Score"].tolist()
Chances_of_admit = df["ChanceAdmit"].tolist()

print(TOEFL_Score)
print(Chances_of_admit)

import numpy as np

# y = m * x + c
# euation of straight line 
#y => output, m => slope, x => input, c=> y intercept
 
#Slope and intercept using pre-built function of Numpy
m, c = np.polyfit(TOEFL_Score, Chances_of_admit, 1)
y = []
for x in TOEFL_Score:
  y_value = m*x + c
  y.append(y_value)

"""Now using the values found let's predict the chances of a person to admit."""

x = 103
y = m * x + c
print(f"Chances of admit if the TOEFL score {x} is {y}")